---
title: "Data Import"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```
Let's import a dataset. 

```{r}
litters_df=
  read_csv("Data/data_import_examples/FAS_litters.csv")
```
lookat your data!!

```{r}
names(litters_df)
```

Update the names in 'litters_df'

```{r}
litters_df=
  janitor::clean_names(litters_df)
```

Look at the data!!

```{r}
litters_df
```

Sometimes skimming data is neat?

```{r}
skimr::skim(litters_df)
```

## Fix the missingness

```{r}
litters_df=
  read_csv("Data/data_import_examples/FAS_litters.csv", na =c("NA", ".",""))
```
## import pups data

```{r}
pups_df=
  read_csv(
    "Data/data_import_examples/FAS_pups.csv", 
    na =c("NA", ".",""), 
    skip = 3)

pups_df=
  janitor::clean_names(pups_df)
```
## Okay what about excel

CSVs are great but sometimes you need excel file

```{r}
mlb_df=
  read_excel("Data/data_import_examples/mlb11.xlsx")
```

Import Lotr word countrs.

```{r}
fotr_df=
  read_excel("Data/data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

## SAS? 

Import the PULSE data

```{r}
pulse_df = read_sas("Data/data_import_examples/public_pulse_data.sas7bdat")

pulse_df=
  janitor::clean_names(pulse_df)
```

## Why do I hate read.csv so much








